version: '3'
services:

#PHP Service app
  app:
    image: nick1846/my-php:latest
    container_name: web
    restart: always
    depends_on:
      - db
    tty: true
    ports:
      - "80:80"  
    working_dir: /var/www/html
    networks:
      - my-network

#pgAdmin Service pgadmin
  pgadmin:
    image: dpage/pgadmin4:4.18
    container_name: pgadmin
    restart: always
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: nick.linuxedu@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres2020
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    networks:
      - my-network
#    volumes:
#    - pgadmin-volume:/var/lib/pgadmin    
 
#PostgreSQL Service db
  db:
    image: nick1846/my-postgres:12.0
    container_name: postgres
    restart: always
    tty: true
    environment:
      POSTGRES_PASSWORD: postgres2020
      PGDATA: /data
#    expose:
#      - 5432
    volumes:
      - postgres-volume:/data
    networks:
      - my-network

#Docker Networks
networks:
  my-network:
    driver: bridge

#Docker Volumes
volumes:
  postgres-volume:
#  pgadmin-volume:
    
  
